"""AI inline completion (ghost text) for the REPL input.

Implements prompt_toolkit's :class:`AutoSuggest` interface to show a grey
"ghost" continuation of what the user is typing, generated by the current
REPL model via :func:`modelbridge.client.chat_once`. The user accepts it
with Tab (wired in ``cli.py``) or the right-arrow / Ctrl-F / Ctrl-E that
prompt_toolkit ships by default.

Design notes
------------

* ``ThreadedAutoSuggest`` wraps this class and runs ``get_suggestion`` in a
  background executor thread on every text change, so the UI never blocks.
  prompt_toolkit cancels stale coroutines when new text arrives, but the
  underlying ``chat_once`` HTTP call still runs to completion — we guard
  against using stale results with a monotonic request id.
* A simple debounce avoids hammering the API on every keystroke: we only
  fire a request if enough idle time has passed since the last fire.
* Slash commands (``/cmd``) and ``@file`` mentions are left to their own
  completers — AI completion only kicks in for free-form prose.
* On repeated failures we back off for the rest of the session so a flaky
  model endpoint never makes the REPL feel broken.

The prompt sent to the model is deliberately short and constrained to make
the model return *only the suffix to append* (no markdown, no explanation),
which is what makes the ghost-text UX feel right.
"""

from __future__ import annotations

import time
from collections.abc import Callable
from threading import Lock
from typing import Any

from prompt_toolkit.auto_suggest import AutoSuggest, Suggestion
from prompt_toolkit.buffer import Buffer
from prompt_toolkit.document import Document

from ..schemas import ChatMessage, text_of


# System instruction for the completion model. Keeping it tiny cuts latency
# and token cost. The constraints ("only the suffix", "no markdown", "≤60
# chars") are what make the suggestion feel like a native inline completion
# rather than a chat reply.
_COMPLETION_SYSTEM = (
    "你是一个 CLI 输入补全器。根据用户当前正在输入的内容和最近对话，"
    "只输出要追加到用户输入末尾的续写文本。"
    "不要解释、不要反引号、不要 markdown 语法、不要换行。最多 60 个字符。"
    "如果无法确定续写内容，输出空字符串。"
)

# Hard caps to keep the completer cheap and snappy.
_MIN_INPUT_CHARS = 3          # don't fire on "a" / "我"
_MAX_INPUT_CHARS = 400        # very long prompts get no completion
_MAX_HISTORY_MESSAGES = 6     # how many recent turns we feed as context
_MAX_SUGGESTION_CHARS = 80    # cap the returned suggestion length
_REQUEST_TIMEOUT_S = 6.0      # short — a slow completion is worse than none
# After this many consecutive failures, give up for the rest of the session
# (the user can restart to retry).
_MAX_CONSECUTIVE_FAILURES = 3


class AIAutoSuggest(AutoSuggest):
    """Ghost-text inline completion backed by the active REPL model.

    Parameters
    ----------
    model_name_provider:
        Zero-arg callable returning the *current* model name (so ``/model``
        switches are reflected immediately). May return ``None`` to disable.
    history_provider:
        Zero-arg callable returning the recent session messages for context.
    enabled_provider:
        Zero-arg callable returning whether AI completion is on (reads
        ``config.prompt.ai_autocomplete`` so users can turn it off).
    debounce_ms:
        Minimum idle time before firing a request (overridable via config).
    chat_fn:
        Injectable for tests — defaults to :func:`modelbridge.client.chat_once`.
    """

    def __init__(
        self,
        *,
        model_name_provider: Callable[[], str | None],
        history_provider: Callable[[], list[ChatMessage]],
        enabled_provider: Callable[[], bool],
        debounce_ms: int = 450,
        chat_fn: Callable[..., tuple[Any, Any]] | None = None,
    ) -> None:
        self._model_name_provider = model_name_provider
        self._history_provider = history_provider
        self._enabled_provider = enabled_provider
        self._debounce_s = max(0.0, debounce_ms / 1000.0)
        self._chat = chat_fn  # lazy default — set on first use to avoid import cycle

        self._lock = Lock()
        # Cache: maps a completed input text → the suffix the model returned.
        # We only ever read entries whose key is a prefix of the current text
        # (so typing more can surface a still-valid suggestion incrementally).
        self._cache: dict[str, str] = {}
        self._last_fire_ts: float = 0.0
        self._last_fire_text: str = ""
        # Monotonic id so a slow in-flight request's result is ignored if the
        # user typed more before it returned.
        self._request_id: int = 0
        # Liveness: after too many failures we stop trying.
        self._consecutive_failures: int = 0
        self._disabled: bool = False

    # ------------------------------------------------------------------
    # AutoSuggest interface
    # ------------------------------------------------------------------

    def get_suggestion(
        self, buffer: Buffer, document: Document
    ) -> Suggestion | None:
        text = document.text_before_cursor

        # Skip rules — let slash / @-file completers own these.
        if not self._should_complete(text):
            return None

        # Fast path: an already-cached suggestion whose key is exactly the
        # current text.
        with self._lock:
            cached = self._cache.get(text)
            if cached is not None:
                return Suggestion(cached) if cached else None
            # Incremental: if the current text extends a cached key, and the
            # extra characters match the cached suggestion's prefix, surface
            # the remaining tail. This makes the ghost text shrink naturally
            # as the user types what the model predicted.
            tail = self._incremental_tail(text)
            if tail is not None:
                return Suggestion(tail) if tail else None

        # Slow path: fire a (debounced) completion request. Because
        # ThreadedAutoSuggest runs this in a worker thread, blocking here
        # for a few seconds won't freeze the UI — the suggestion simply
        # appears once the request returns.
        suffix = self._fetch(text)
        if suffix is None:
            return None
        return Suggestion(suffix) if suffix else None

    # ------------------------------------------------------------------
    # Decision logic
    # ------------------------------------------------------------------

    def _should_complete(self, text: str) -> bool:
        """Whether AI completion should fire for this input."""
        if self._disabled:
            return False
        try:
            if not self._enabled_provider():
                return False
        except Exception:
            return False
        stripped = text.strip()
        if len(stripped) < _MIN_INPUT_CHARS:
            return False
        if len(text) > _MAX_INPUT_CHARS:
            return False
        # Slash commands have their own completer.
        line = text.rsplit("\n", 1)[-1]
        if line.startswith("/"):
            return False
        # @file mentions have their own completer — skip while typing one.
        if "@" in line:
            return False
        # Multiline input: only complete when the user is on the first line
        # and it's still a single-line thought (avoids weird mid-block ghosts).
        if "\n" in text:
            return False
        return True

    def _incremental_tail(self, text: str) -> str | None:
        """If ``text`` extends a cached key along the cached suggestion, return the tail.

        Returns ``None`` when no incremental match is possible.
        """
        for key, suggestion in self._cache.items():
            if not suggestion:
                continue
            if text.startswith(key) and text != key:
                extra = text[len(key):]
                if suggestion.startswith(extra):
                    return suggestion[len(extra):]
        return None

    def _fetch(self, text: str) -> str | None:
        """Debounced, guarded call to the model. Returns the suffix or ``None``."""
        now = time.monotonic()
        # Debounce: skip if we fired too recently for a different/longer text.
        # Re-firing for the *same* text is allowed (idempotent cache fill).
        with self._lock:
            if (
                text != self._last_fire_text
                and (now - self._last_fire_ts) < self._debounce_s
            ):
                return None
            if text == self._last_fire_text and self._cache.get(text) is not None:
                return self._cache[text]
            self._last_fire_ts = now
            self._last_fire_text = text
            self._request_id += 1
            my_id = self._request_id

        # Resolve the model lazily.
        try:
            model_name = self._model_name_provider()
        except Exception:
            return None
        if not model_name:
            return None

        # Build a minimal prompt: a few recent messages for context + the
        # user's current input. The system instruction constrains the output.
        try:
            history = self._history_provider() or []
        except Exception:
            history = []
        history = [m for m in history if m.role != "system"][-_MAX_HISTORY_MESSAGES:]

        prompt = _build_prompt(text, history)

        if self._chat is None:
            from ..client import chat_once as _chat_once
            self._chat = _chat_once

        try:
            _entry, resp = self._chat(
                prompt=prompt,
                model_name=model_name,
                system=_COMPLETION_SYSTEM,
                thinking=False,
                timeout=_REQUEST_TIMEOUT_S,
                verbose_label="autocomplete",
            )
        except Exception:
            with self._lock:
                self._consecutive_failures += 1
                if self._consecutive_failures >= _MAX_CONSECUTIVE_FAILURES:
                    self._disabled = True
            return None

        with self._lock:
            # Stale guard: another request was fired after ours.
            if my_id != self._request_id:
                return None
            self._consecutive_failures = 0
            suggestion = _extract_suffix(text, resp)
            # Cap length so a chatty model can't dump a paragraph.
            if len(suggestion) > _MAX_SUGGESTION_CHARS:
                suggestion = suggestion[:_MAX_SUGGESTION_CHARS]
            # An ASCII↔CJK boundary glues words together when Tab accepts
            # the ghost text ("serve" + "你帮我…" → "serve你帮我…"). Insert
            # the separator the model omitted so accepted input stays sane.
            suggestion = _apply_boundary_space(text, suggestion)
            self._cache[text] = suggestion
            return suggestion or None


def _is_cjk_char(ch: str) -> bool:
    """CJK ideographs / radicals / fullwidth forms — the ranges that fuse
    visually with adjacent ASCII when no space separates them."""
    if not ch:
        return False
    o = ord(ch)
    return (
        0x2E80 <= o <= 0x9FFF      # CJK radicals + Unified Ideographs
        or 0x3000 <= o <= 0x303F   # CJK punctuation
        or 0xFF00 <= o <= 0xFFEF   # fullwidth forms
    )


def _apply_boundary_space(buffer_text: str, suggestion: str) -> str:
    """Prefix a space when gluing would fuse an ASCII and a CJK word.

    Pure-CJK continuations (中文接中文) and ASCII-to-ASCII (code completion)
    are left untouched — Chinese doesn't take inner spaces and code must not
    get any.
    """
    if not buffer_text or not suggestion:
        return suggestion
    left, right = buffer_text[-1], suggestion[0]
    if left.isspace() or right.isspace():
        return suggestion
    if _is_cjk_char(left) != _is_cjk_char(right):
        return " " + suggestion
    return suggestion


# ---------------------------------------------------------------------------
# Prompt construction + response extraction (pure → unit-testable)
# ---------------------------------------------------------------------------

def _build_prompt(current_input: str, history: list[ChatMessage]) -> str:
    """Build the user-turn prompt for the completion model.

    Format: a compact transcript (so the model knows what the user is working
    on) followed by the line to complete. Keeping the transcript flat (one
    line per turn) holds token cost down.
    """
    lines: list[str] = []
    for m in history:
        body = (text_of(m.content) or "").strip().replace("\n", " ")
        if not body:
            continue
        if len(body) > 200:
            body = body[:200] + "…"
        who = "用户" if m.role == "user" else "AI"
        lines.append(f"{who}: {body}")
    transcript = "\n".join(lines)
    if transcript:
        return (
            f"最近对话:\n{transcript}\n\n"
            f"用户当前正在输入(尚未发送):\n{current_input}\n\n"
            f"只输出要追加到末尾的续写文本:"
        )
    return f"用户当前正在输入(尚未发送):\n{current_input}\n\n只输出要追加到末尾的续写文本:"


def _extract_suffix(original_input: str, resp: object) -> str:
    """Pull the suggestion suffix out of a ChatResponse.

    The model is told to return *only* the suffix; in practice it sometimes
    re-emits the input or wraps in quotes, so we defensively strip:
      * leading/trailing whitespace and surrounding quotes/backticks
      * a leading re-statement of the original input
    """
    # ChatResponse has .content (str | None) — access defensively for tests.
    raw = getattr(resp, "content", None)
    if not isinstance(raw, str):
        return ""
    text = raw.strip()
    # Strip surrounding quotes / backticks the model may have added.
    while len(text) >= 2 and text[0] in "\"'`" and text[-1] == text[0]:
        text = text[1:-1].strip()
    # If the model echoed the whole input + a suffix, keep only the suffix.
    if text.startswith(original_input.strip()):
        text = text[len(original_input.strip()):]
    # No newlines inside a single-line completion.
    text = text.replace("\n", " ").strip()
    return text


__all__ = ["AIAutoSuggest"]
